server:
  port: 8899

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server: 
    wait-time-in-ms-when-sync-empty: 3000

security:
  user:
    password: password

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nobble_oauth
    username: kaushik
    password: root@123
    driver-class: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: validate

logging:
  level:
    ROOT: ERROR
    org.springframework.web: ERROR
    com.enrico.microservices: DEBUG
  file:  /tmp/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
