server:
  port: 8899

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.200:8761/eureka/

security:
  user:
    password: password

spring:
  datasource:
    url: jdbc:mysql://192.168.1.201:3306/demo_micro
    username: root
    password: root
    driver-class: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
