server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

authserver:
    hostname: localhost
    port: 8899
    contextPath: userauth

# Note that the "/user" endpoint needs to provide the principle of the logged in user (/me endpoint)
spring:
  oauth2:
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/me
      preferTokenInfo: false 
    client:
      accessTokenUri: http://${authserver.hostname}:${authserver.port}/oauth/token
      userAuthorizationUri: http://${authserver.hostname}:${authserver.port}/oauth/authorize
      clientId: client
